version: '3.9'

services:
  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    restart: always
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}'
      - '${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data

volumes:
  minio-data:
    driver: local
